# Generated by Django 5.0.3 on 2024-03-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomOposicion', models.CharField(max_length=50)),
                ('OpoVisible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'OPOSICION',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrueba', models.CharField(max_length=50)),
                ('NumPreguntas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('PruVisible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PRUEBA',
            },
        ),
        migrations.AddField(
            model_name='temario',
            name='Archivo',
            field=models.FileField(default='', upload_to='temario/'),
        ),
        migrations.AlterModelTable(
            name='temario',
            table='TEMARIO',
        ),
        migrations.AddField(
            model_name='temario',
            name='IdOposicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oposicion.oposicion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('PregAcertadas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('PregFalladas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('PregBlanco', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Tiempo', models.IntegerField()),
                ('IdPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.prueba')),
            ],
            options={
                'db_table': 'PROGRESO',
            },
        ),
        migrations.CreateModel(
            name='Formado_por',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdTemario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.temario')),
                ('IdPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.prueba')),
            ],
            options={
                'db_table': 'FORMADO_POR',
            },
        ),
        migrations.AddConstraint(
            model_name='formado_por',
            constraint=models.UniqueConstraint(fields=('IdTemario', 'IdPrueba'), name='pk_IdTemario_IdPrueba'),
        ),
    ]
