# Generated by Django 5.0.3 on 2024-03-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomOposicion', models.CharField(max_length=50)),
                ('OpoVisible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrueba', models.CharField(max_length=50)),
                ('NumPreguntas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('PruVisible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agrupa_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdTemario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.temario')),
                ('IdOposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.oposicion')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('PregAcertadas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('PregFalladas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('PregBlanco', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Tiempo', models.IntegerField()),
                ('IdPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.prueba')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agrupa_en',
            constraint=models.UniqueConstraint(fields=('IdTemario', 'IdOposicion'), name='pk_IdTemario_IdOposicion'),
        ),
    ]
