# Generated by Django 5.0.3 on 2024-03-30 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0002_oposicion_prueba_temario_archivo_alter_temario_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='Tiempo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
