# Generated by Django 5.0.3 on 2024-03-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0002_oposicion_prueba_agrupa_en_progreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formado_por',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.prueba')),
                ('IdTemario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.temario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formado_por',
            constraint=models.UniqueConstraint(fields=('IdTemario', 'IdPrueba'), name='pk_IdTemario_IdPrueba'),
        ),
    ]
