# Generated by Django 5.0.3 on 2024-03-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0003_formado_por_formado_por_pk_idtemario_idprueba'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agrupa_en',
            table='AGRUPA_EN',
        ),
        migrations.AlterModelTable(
            name='formado_por',
            table='FORMADO_POR',
        ),
        migrations.AlterModelTable(
            name='oposicion',
            table='OPOSICION',
        ),
        migrations.AlterModelTable(
            name='progreso',
            table='PROGRESO',
        ),
        migrations.AlterModelTable(
            name='prueba',
            table='PRUEBA',
        ),
    ]
