# Generated by Django 5.0.3 on 2024-03-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0004_alter_agrupa_en_table_alter_formado_por_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temario',
            table='TEMARIO',
        ),
    ]
