# Generated by Django 5.0.3 on 2024-03-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='USUARIO',
        ),
    ]
