# Generated by Django 5.0.3 on 2024-03-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('oposicion', '0003_formado_por_formado_por_pk_idtemario_idprueba'),
        ('usuarios', '0003_rename_usuario_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
