# Generated by Django 5.0.3 on 2024-03-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
