# Generated by Django 5.0.3 on 2024-03-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
    ]
